# Generated by Django 5.2.7 on 2025-10-27 07:33

import contacts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(blank=True, max_length=30)),
                ('file', models.FileField(max_length=500, upload_to=contacts.models.client_upload_to)),
                ('nombre_original', models.CharField(max_length=255)),
                ('confidencial', models.BooleanField(default=False)),
                ('sha256', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('cita', 'Cita'), ('visita', 'Visita'), ('reunion', 'Reunión')], default='cita', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=150)),
                ('texto', models.TextField()),
                ('importante', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inicio', models.DateField()),
                ('fin', models.DateField(blank=True, null=True)),
                ('salario_bruto_anual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coste_empresa_pct', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('plus_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tarifa_interna_hora', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('horas_totales', models.DecimalField(decimal_places=2, max_digits=5)),
                ('entrada', models.TimeField(blank=True, null=True)),
                ('salida', models.TimeField(blank=True, null=True)),
                ('descanso_minutos', models.PositiveIntegerField(default=0)),
                ('fuente', models.CharField(blank=True, max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LocationLite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='LocationRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodo', models.DateField()),
                ('ingresos', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(blank=True, max_length=30)),
                ('file', models.FileField(max_length=500, upload_to=contacts.models.supplier_upload_to)),
                ('nombre_original', models.CharField(max_length=255)),
                ('confidencial', models.BooleanField(default=False)),
                ('sha256', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(max_length=50)),
                ('codigo', models.CharField(blank=True, max_length=80)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('adjunto', models.FileField(blank=True, null=True, upload_to=contacts.models.supplier_cert_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=150)),
                ('texto', models.TextField()),
                ('importante', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku_proveedor', models.CharField(max_length=120)),
                ('producto_sku_interno', models.CharField(blank=True, max_length=120)),
                ('precio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('moneda', models.CharField(default='EUR', max_length=10)),
                ('min_qty', models.PositiveIntegerField(default=1)),
                ('lead_time_dias', models.PositiveIntegerField(default=0)),
                ('valido_desde', models.DateField()),
                ('valido_hasta', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='worklocation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='worklocation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='worklocation',
            name='org',
        ),
        migrations.RemoveField(
            model_name='worklocation',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='ubicacion_laboral',
        ),
        migrations.AddField(
            model_name='attachment',
            name='periodo_nomina',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='centro_coste',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='objetivo_horas_mes',
            field=models.PositiveIntegerField(default=160),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['contact', 'categoria', 'periodo_nomina'], name='contacts_at_contact_14c422_idx'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(condition=models.Q(('categoria', 'nomina')), fields=('contact', 'categoria', 'periodo_nomina'), name='unique_payslip_per_month'),
        ),
        migrations.AddField(
            model_name='clientattachment',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='clientattachment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientattachment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientevent',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='clientevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientevent',
            name='empleado_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientevent',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AddField(
            model_name='clientevent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientnote',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='clientnote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientnote',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeecompensation',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensaciones', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='employeecompensation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeecompensation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeehours',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_trabajadas', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='employeehours',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeehours',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locationlite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locationlite',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_lite', to='core.organization'),
        ),
        migrations.AddField(
            model_name='locationlite',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='contacts.locationlite'),
        ),
        migrations.AddField(
            model_name='locationrevenue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locationrevenue',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='contacts.locationlite'),
        ),
        migrations.AddField(
            model_name='locationrevenue',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_revenues', to='core.organization'),
        ),
        migrations.AddField(
            model_name='locationrevenue',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierattachment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierattachment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_docs', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='supplierattachment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suppliercertification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suppliercertification',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='suppliercertification',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suppliernote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suppliernote',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_notes', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='suppliernote',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierprice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierprice',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AddField(
            model_name='supplierprice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='supplierprice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='WorkLocation',
        ),
        migrations.AddIndex(
            model_name='employeecompensation',
            index=models.Index(fields=['contact', 'inicio'], name='contacts_em_contact_65163c_idx'),
        ),
        migrations.AddIndex(
            model_name='employeehours',
            index=models.Index(fields=['contact', 'fecha'], name='contacts_em_contact_d57049_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeehours',
            unique_together={('contact', 'fecha', 'referencia')},
        ),
        migrations.AddIndex(
            model_name='locationlite',
            index=models.Index(fields=['org', 'nombre'], name='contacts_lo_org_id_ead2ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='locationlite',
            unique_together={('org', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='locationrevenue',
            index=models.Index(fields=['location', 'periodo'], name='contacts_lo_locatio_a2e106_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='locationrevenue',
            unique_together={('location', 'periodo')},
        ),
        migrations.AddIndex(
            model_name='suppliercertification',
            index=models.Index(fields=['supplier', 'tipo', 'fecha_caducidad'], name='contacts_su_supplie_9b4f14_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierprice',
            index=models.Index(fields=['supplier', 'sku_proveedor', 'valido_desde'], name='contacts_su_supplie_c2b60e_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierprice',
            index=models.Index(fields=['org'], name='contacts_su_org_id_0ee970_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierprice',
            unique_together={('supplier', 'sku_proveedor', 'valido_desde')},
        ),
    ]
