# Generated by Django 5.2.7 on 2025-11-03 16:53

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_clientattachment_clientevent_clientnote_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['org', 'nombre'], name='contacts_co_org_id_d9bac5_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['org', 'telefono'], name='contacts_co_org_id_b53062_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['org', 'updated_by'], name='contacts_co_org_id_bd02c0_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['org', 'activo'], name='contacts_co_org_id_784e04_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['org', 'bloqueado'], name='contacts_co_org_id_c4d0c3_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['etiquetas'], name='idx_contacts_etiquetas_gin'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('org', 'tipo', 'email'), name='uq_contact_email_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('documento_id', ''), _negated=True), fields=('org', 'documento_id'), name='uq_contact_docid_nonempty'),
        ),
    ]
