# Generated by Django 5.2.7 on 2025-11-25 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(default='PREATOR', max_length=200)),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reply_to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bcc_on_outgoing', models.EmailField(blank=True, max_length=254, null=True)),
                ('send_system_emails', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to='core.organization')),
            ],
        ),
    ]
