# Generated by Django 5.2.7 on 2025-11-17 15:14

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, default='', max_length=240)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('category', models.CharField(choices=[('rent', 'Alquiler'), ('payroll', 'Nóminas'), ('utilities', 'Suministros'), ('taxes', 'Impuestos'), ('services', 'Servicios externos'), ('other', 'Otros')], default='other', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrgFinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('opening_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('opening_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('sales_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('expenses_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_years', to='core.organization')),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('organization', 'year')},
            },
        ),
    ]
