# Generated by Django 5.2.7 on 2025-11-12 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0003_alter_contact_unique_together_and_more'),
        ('core', '0001_initial'),
        ('sales', '0002_quote_quoteline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, default='', max_length=9)),
                ('is_important', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.invoice')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.organization')),
            ],
            options={
                'ordering': ['start'],
                'indexes': [models.Index(fields=['org', 'start', 'end'], name='agenda_even_org_id_6d63fa_idx'), models.Index(fields=['org', 'is_important'], name='agenda_even_org_id_1af8e5_idx'), models.Index(fields=['org', 'contact', 'start'], name='agenda_even_org_id_67de11_idx')],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('body', models.TextField(blank=True, default='')),
                ('is_task', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=9)),
                ('is_important', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.invoice')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.organization')),
            ],
            options={
                'ordering': ['-is_pinned', 'due_date', '-created_at'],
                'indexes': [models.Index(fields=['org', 'due_date'], name='agenda_note_org_id_cb64a1_idx'), models.Index(fields=['org', 'is_important'], name='agenda_note_org_id_438fd3_idx'), models.Index(fields=['org', 'is_pinned'], name='agenda_note_org_id_f1d75f_idx'), models.Index(fields=['org', 'contact', 'due_date'], name='agenda_note_org_id_a331a5_idx')],
            },
        ),
    ]
