# Generated by Django 5.2.7 on 2025-11-19 11:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0003_alter_contact_unique_together_and_more'),
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Identificador interno del pedido (ej: PO-2025-0001)', max_length=32)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partially_received', 'Partially received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=24)),
                ('total_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes_internal', models.TextField(blank=True, default='')),
                ('notes_supplier', models.TextField(blank=True, default='')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
                ('supplier', models.ForeignKey(help_text='Debe ser un contacto de tipo proveedor (se filtrará en la UI/API).', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='contacts.contact')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'unique_together': {('org', 'number')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=240)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=16)),
                ('uom', models.CharField(default='unidad', max_length=24)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('line_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('line_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchaseorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('supplier_invoice_number', models.CharField(blank=True, default='', help_text='Número tal cual aparece en la factura del proveedor.', max_length=64)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=16)),
                ('total_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Opcional: si la factura viene de un pedido.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='purchases.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='contacts.contact')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'unique_together': {('org', 'number')},
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=240)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=16)),
                ('uom', models.CharField(default='unidad', max_length=24)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('line_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('line_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.supplierinvoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_lines', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('transfer', 'Transfer'), ('card', 'Card'), ('cash', 'Cash')], default='transfer', max_length=16)),
                ('notes', models.CharField(blank=True, default='', max_length=240)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='purchases.supplierinvoice')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
