# Generated by Django 5.2.7 on 2025-11-08 10:52

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0003_alter_contact_unique_together_and_more'),
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('done', 'Done')], default='draft', max_length=16)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.contact')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'unique_together': {('org', 'number')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=240)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=16)),
                ('uom', models.CharField(default='unidad', max_length=24)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.deliverynote')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(default='A', max_length=8)),
                ('number', models.IntegerField()),
                ('date_issue', models.DateField(default=django.utils.timezone.now)),
                ('billing_address', models.CharField(blank=True, default='', max_length=240)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=16)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('totals_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('totals_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('verifactu_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('ack', 'Ack'), ('error', 'Error')], default='pending', max_length=16)),
                ('verifactu_hash', models.CharField(blank=True, default='', max_length=128)),
                ('verifactu_sent_at', models.DateTimeField(blank=True, null=True)),
                ('verifactu_ack_payload', models.TextField(blank=True, default='')),
                ('verifactu_error', models.TextField(blank=True, default='')),
                ('verifactu_qr_text', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.contact')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
            ],
            options={
                'unique_together': {('org', 'series', 'number')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=240)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=16)),
                ('uom', models.CharField(default='unidad', max_length=24)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('transfer', 'Transfer'), ('card', 'Card'), ('cash', 'Cash')], default='transfer', max_length=16)),
                ('notes', models.CharField(blank=True, default='', max_length=240)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.invoice')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(default='A', max_length=8)),
                ('year', models.IntegerField()),
                ('last_number', models.IntegerField(default=0)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
            ],
            options={
                'unique_together': {('org', 'series', 'year')},
            },
        ),
    ]
